# Generated by Django 4.2.7 on 2023-11-15 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Competence',
            new_name='Skill',
        ),
        migrations.RenameModel(
            old_name='ProfilUtilisateur',
            new_name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='experienceprofessionnelle',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Projet',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='date_obtention',
            new_name='date_achieved',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='nom',
            new_name='issuing_organization',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='organisme',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='certification',
            old_name='utilisateur',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='diplome',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='annee_obtention',
            new_name='graduation_year',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='etablissement',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='utilisateur',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='utilisateur',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='ExperienceProfessionnelle',
        ),
    ]
